### ISSUE TITLE
error when specifying fault_slip_vector in create_and_add_fault

### ISSUE THREAD

**Issue by gpirot** [Loop3D/LoopStructural#107]
### Describe your issue

Hi Lachie,

Providing a fault_slip_vector during the creation of a fault causes an error.
Without, or when commenting the input, there is no issue.

[test-slipvector.zip](https://github.com/Loop3D/LoopStructural/files/8000453/test-slipvector.zip)

### Minimal reproducing code example

```python
See the attached example.
```

### Error message

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-02dd0df01bea> in <module>
     13                                     steps=4,
     14                                     interpolatortype='PLI',
---> 15                                   buffer=0.3)
     16 ixcf =1
     17 flt2 = model.create_and_add_fault(df_faults.loc[ixcf,'Name'],

C:\ProgramData\Anaconda3\lib\site-packages\LoopStructural\modelling\core\geological_model.py in create_and_add_fault(self, fault_surface_data, displacement, tol, fault_slip_vector, fault_center, major_axis, minor_axis, intermediate_axis, faultfunction, **kwargs)
   1407                     .to_numpy()
   1408                 )
-> 1409         if np.any(np.isnan(fault_slip_vector)):
   1410             logger.warning("Fault slip vector is nan, estimating from fault normal")
   1411             strike_vector, dip_vector = get_vectors(fault_normal_vector[None, :])

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by lachlangrose** [comment]
Hi Guillaume,

That error message is from numpy isnan function, it is caused by passing a non numerical data type to the isnan function. If you modify your fault_slip_vector to be a number as opposed to an object it will work. (just cast as int e.g. fault_slip_vector.astype(float) )

cheers

**Comment by gpirot** [comment]
Hi Lachie,
Sorry, but I do not understand: how do I represent a vector by a number?
And from the doc https://loop3d.github.io/LoopStructural/user_guide/fault_modelling.html 
'fault_slip_vector' is supposed to be a 'numpy array describing the fault slip'.

**Comment by lachlangrose** [comment]
If you look at the dtype of the numpy array it is an object. So python does not interpret it as a number... change the datatype to a float.

**Comment by gpirot** [comment]
Ok, thanks for the precision. However, should we not expect a similar behavior for the fault_center parameter?

**Comment by lachlangrose** [comment]
I don't think the fault centre is checked for nan, so it probably gets cast to a float at some point. I'll have to add in a converter for these inputs.
