### ISSUE TITLE
Is there another link to the documentation?

### ISSUE THREAD

**Issue by gpirot** [Loop3D/LoopStructural#129]
The following one https://loop3d.github.io/LoopStructural/ is currently not working.

I get the following:
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by lachlangrose** [comment]
The documentation wasn't building correctly for the last release. It will be update soon. You can build the documentation locally using the docker image in the docs folder and the build_docs.sh script.

**Comment by lachlangrose** [comment]
Documentation is back online.

**Comment by gpirot** [comment]
Great !
