### ISSUE TITLE
Installs all dependencies, no pictures appear？

### ISSUE THREAD

**Issue by MasterVV** [Loop3D/LoopStructural#132]
All libraries have been installed. Case 1 can run, and other cases cannot be mapped. I don't know where the problem occurs，thank you auther

**Comment by lachlangrose** [comment]
Hi MasterVV can you please give me a bit more information. If possible provide me with a minimal working example, your python version, the libraries you have installed, what the problem is... is there an error or can you just not see the visualisation?

**Comment by MasterVV** [comment]
> Hi MasterVV can you please give me a bit more information. If possible provide me with a minimal working example, your python version, the libraries you have installed, what the problem is... is there an error or can you just not see the visualisation?

Thank you for your reply. I installed Python 3.9.10, numpy 1.23.4, pandas 1.5.1, scipy 1.9.3, scikit-fmm 2022.8.15, scikit-image 0.19.3, scikit-learn 1.1.3, matplotlib 3.6.1, lavavu 1.8.35, surfepy 0.51. matplotlib 3.6.1. Don 't know if this version conflicts ? 
As mentioned earlier, Case 1 can operate normally, and the diagram based on matplotlib is normal. 
![1666927317916](https://user-images.githubusercontent.com/50104622/198497788-3ba142fe-6ddf-472a-bc93-c69add79bed3.jpg)

The problem is 1b.Implicit surface modelling, based on viewer.display ( ), the picture does not appear. My other computer is also so installed can run normally, so do not know where the prob
<img width="890" alt="2" src="https://user-images.githubusercontent.com/50104622/198565451-62b392be-5662-4e86-8d4a-7bd658a6ac31.png">
lem ?

**Comment by MasterVV** [comment]
After the computer is updated, the problem has been solved。
