### ISSUE TITLE
[Question] how to export as vtk .ts?

### ISSUE THREAD

**Issue by GeoMattB** [Loop3D/LoopStructural#135]
Hi again,
I searched the loop Structural docs and couldn't find anything obvious that allows me to export the fault surfaces I'm generating. 
I can get it from vtk to .ts by myself if there isn't already a .ts output built.

Thanks
Matt

**Comment by markjessell** [comment]
Hi Matt

there may be something built in but the notebooks in the map2loop repository give examples for a bigger range of outputs:

https://github.com/Loop3D/map2loop2-notebooks/blob/master/Example%202%20-%20Draw%20Your%20Own%20Area.ipynb


and

https://github.com/Loop3D/map2loop2-notebooks/blob/master/Utility%202%20-%20Exporters.ipynb

in particular

cheers

Mark

--
Mark Jessell |WA Fellow/Winthrop Professor | Centre for Exploration Targeting
M006 | 35 Stirling Highway | Crawley WA 6009 Australia
Tel +61 8 6488 5803<tel:%2B61%208%206488%205803> | Fax +61 8 6488 1178<tel:%2B61%208%206488%201178>
E-mail ***@***.***<https://webmail.staff.uwa.edu.au/owa/redir.aspx?C=4xvWZ6_yskmY0MpvWKb98mi_y8Pxp9BIS4_ouYDQLG_JgfX75yvqiy_wFhvxRiHJVFGwvtlBpek.&URL=mailto%3aMark.Jessell%40uwa.edu.au>|www.cet.edu.au<https://webmail.staff.uwa.edu.au/owa/redir.aspx?C=4xvWZ6_yskmY0MpvWKb98mi_y8Pxp9BIS4_ouYDQLG_JgfX75yvqiy_wFhvxRiHJVFGwvtlBpek.&URL=http%3a%2f%2fwww.cet.edu.au%2f>

[The University of Western Australia]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.web.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Fuwa-logo&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4fNvQvXY7UjY8ot8A%2F54jTqkMOuZrSZK7XLnHNCVJoI%3D&reserved=0>

[UWA on Facebook]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Ffacebook&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3oABqCWTa%2F6Mk%2FAZLAXj99gW7jpqMJHezz%2BVTNYy%2B6c%3D&reserved=0>  [UWA on Twitter] <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Ftwitter&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SjveeZhWr7DzcbFrfdiJcrC82gDHlIR3%2BNcj1danAsM%3D&reserved=0>   [UWA on Youtube] <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Fyoutube&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j4OT4N%2Bp65329MrED8q0d%2BfjkIWLX6p0PNoZ%2FpBt3lo%3D&reserved=0>   [UWA on Linked In] <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.web.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Flinkedin&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CpLBS548IoJg2pcgZvyoztGjG5%2BVPPGrYL6RNocxzQk%3D&reserved=0>   [UWA on Instagram] <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.web.uwa.edu.au%2Funiversity-campaigns-resources%2Femailsig2015%2Finstagram&data=05%7C01%7Cmark.jessell%40uwa.edu.au%7C7d35bb43063944530ff008dac3a48aa8%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638037408735356432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v6BuppFVfpLp5oSzXfBed8Zg01SzQuKIUR0lwRTfsBY%3D&reserved=0>





[signature_2335985396]

We acknowledge we are situated on Noongar land, and that Noongar people remain the spiritual and cultural custodians of their land, and continue to practise their values, languages, beliefs and knowledge. We pay our respects to the traditional owners of the lands on which we live and work across Western Australia and Australia.

________________________________
From: MattB ***@***.***>
Sent: Friday, 25 November 2022 9:48 AM
To: Loop3D/LoopStructural ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Loop3D/LoopStructural] [Question] how to export as vtk .ts? (Issue #135)


Hi again,
I searched the loop Structural docs and couldn't find anything obvious that allows me to export the fault surfaces I'm generating.
I can get it from vtk to .ts by myself if there isn't already a .ts output built.

Thanks
Matt

**Comment by lachlangrose** [comment]
Hi Matt,

I haven't written a ts exporter yet but there is #100 that I need to integrate into LoopStructural. I personally don't use external visualization so it hasn't been a priority but I will aim to do it in the near future. It will follow a similar pattern to the vtk exporter.

Cheers

**Comment by GeoMattB** [comment]
Thank Lachlan,
I'm just using LoopStructural from a pip install and I'm getting

ModuleNotFoundError: No module named 'LoopStructural.export'

This is the same docker container I'm able to build the faults in, something is off with my install I think

**Comment by lachlangrose** [comment]
Umm that may be because there is no __init__.py file in the module, can you directly import the files 

`from LoopStructural.export.exporters import write_feat_surfs`

I haven't actually used this module but I'll take a look and see if I can workout what is going on.

**Comment by GeoMattB** [comment]
Hi Lachlan, I can see 'export' in the directory structure but LoopStructural doesn't have export available anywhere I can find it.
I may be doing something wrong??? 

![image](https://user-images.githubusercontent.com/29564171/203894264-d1463821-31d4-47a3-ab51-f47176f5cf7b.png)

**Comment by lachlangrose** [comment]
Does this work
```
from LoopStructural.export.exporters import write_feat_surfs
```

For me it gives an error needing pyevtk but if you have the dependencies it should work. I haven't merged the TS code into the master branch currently so you'll have to wait for that.

**Comment by GeoMattB** [comment]
![image](https://user-images.githubusercontent.com/29564171/203895364-375d753d-2405-421d-81a7-2650c143fd51.png)

**Comment by lachlangrose** [comment]
That is odd, you'll have to leave that with me and I'll try to fix it up.

**Comment by GeoMattB** [comment]
Hi Lachlan, 
Had another look at it a few minutes ago and I was able to get it working after a reinstall. I'm not sure if it was adding the init file to that export directory or installing surfe but that line just started working.

![image](https://user-images.githubusercontent.com/29564171/203909199-bfe734d5-7995-47e4-a14f-23fdd75621ff.png)
Also... there's a typo in exporters.py

![image](https://user-images.githubusercontent.com/29564171/203909664-6d4cf487-bdf8-476d-a636-0fb6cfaca398.png)

**Comment by lachlangrose** [comment]
Thanks Matt, I'll fix that up
