### ISSUE TITLE
How can I get the input data for LoopStructural?

### ISSUE THREAD

**Issue by lj-cug** [Loop3D/LoopStructural#152]
I have installed and run the LoopStructural examples correctly. Now I wonder how can I get the fault input data to build geologic model?  I have the seismic data (seg-y file) and well log (.las) files. I always interpret the fault data using Petrel software, and only the fault xyz data, which is not enough for building geological model in LoopStructural. There's so much input data examples in the example, but I'm confused about them. 
Map2loop can generate the input data for LoopStructural, but this is for West Australia geological database. The input data include many information, such as gradient, orientation (dip, azimuth, polarity), which are out of the scope for many seismic interpretation software. Meanwhile, some friends are also confused about the input data for GemPy project, like:
https://github.com/cgre-aachen/gempy/issues/99
https://github.com/cgre-aachen/gempy/issues/225
https://github.com/cgre-aachen/gempy/issues/553
So it seems the way for getting the input data should have some guidance (jupyter notebook?). Could you give me some guidance? Thanks!

**Comment by lachlangrose** [comment]
Hi @lj-cug,

Thanks for the question. To model faults using LoopStructural you need to have both the location of the fault surface (these are the points you have interpreted from the seismic) and the orientation of the fault at one location. If you haven't actually observed the orientation of the fault it is possible to approximate this by fitting a plane using least squares to the points that you have interpolated. 

@AngRodrigues  has an example in this notebookhttps://github.com/Loop3D/Kalgoorlie_3Dmodelling/blob/main/GA_2022_presentation/GA_2022_interactive_presentation.ipynb


@GeoMattB has also opened #138 which will integrate the code from @AngRodrigues into the fault builder class, but I haven't had a chance to do this yet...
 
I hope this helps.
