### ISSUE TITLE
Example input file requested for importing point data into LoopStructural [Question]

### ISSUE THREAD

**Issue by vfreedman** [Loop3D/LoopStructural#157]
I have executed the tutorial where data are randomly generated but I could use some help with an example script and data file used to build a new model.  Would someone be able to provide this information, please?

Vicky

**Comment by lachlangrose** [comment]
Hi Vicky,

I'm unsure what you are trying to do with LoopStructural, so there are a few different ways to format the input data. If you want to build a sign distance (scalar) field then the data can be formatted following this guide:

https://loop3d.org/LoopStructural/user_guide/input_data.html

if you are trying to build a model from a map then it requires more processing. But if you can extract the data into files representing:

- basal contact between units 
- orientation of stratigraphy
- fault location
- fault orientation
- fault interactions (a text file showing the pairs of faults which interesect and where the intersection is a splay or abutting relationship
- stratigraphic order

These files can be used in the process input data class - https://loop3d.org/LoopStructural/_autosummary/LoopStructural.modelling.ProcessInputData.html

an example is here, its not building using the documentation build but you should be able to run the python file. https://github.com/Loop3D/LoopStructural/blob/master/examples/4_advanced/plot_model_from_geological_map.py

Let me know if you have any other questions.

Cheers,

Lachlan
