### ISSUE TITLE
How to export generated models to .obj files

### ISSUE THREAD

**Issue by fjphhxx** [Loop3D/LoopStructural#160]
Hello lachlangrose：
I read in your paper that the generated model can be exported as a .vtk or .obj file, but I didn't find it in the documentation.
Can you tell me how to export the generated fault model, thanks!
![image](https://github.com/Loop3D/LoopStructural/assets/69345724/a4a81c42-9de1-49be-95c1-29f818b5344b)
![断层面](https://github.com/Loop3D/LoopStructural/assets/69345724/54dcc341-cf19-47f7-b88e-0e7a468121d9)

**Comment by fjphhxx** [comment]
Hello Lachlan Grose：
I would like to be able to export the generated stratigraphic and fault models as .obj files, how should I do this?

**Comment by lachlangrose** [comment]
hi @fjphhxx there is the possibility of passing a callback function to the .add_surface methods of the visualisation library. Just add `view.add_isosurface(model['featurename'],value=0, callback = yourfunction)`
Where yourfunction is a custom exporter to obj format.
```Python
def yourfunction(verts,tri,name):
  save_vert(verts,name)
  save_tris(tris,name)
```

If you want vtk surfaces you can use the VtkModelExporter to export the surfaces to vtk.

Good luck!

**Comment by fjphhxx** [comment]
Sorry, I still don't quite understand what you mean. Can you expand on it.

**Comment by lachlangrose** [comment]
Hi,

If you can create a function that generates an obj file from the vertices
and triangles this can be passed to loop.

Cheers

**Comment by fjphhxx** [comment]
Hello Lachlan Grose：
First of all, thank you for answering my question. I have one more question. How can I make the hanging wall and footwall
of the fault.I can't do the following picture.
![image](https://github.com/Loop3D/LoopStructural/assets/69345724/9bfc9170-486e-4d3f-9a29-cf9f536d3e0f)

I would be very grateful if you could provide the code for this example. I am learning from the example. 
Thank you.

**Comment by lachlangrose** [comment]
Are you using the notebook from the paper?

**Comment by fjphhxx** [comment]
This is a picture from your paper. Can you give me the code for this example, I want to learn it.I am using the notebook.Thank you.
