### ISSUE TITLE
[Question]How to Generate Stratigraphic Upper and Lower Plates

### ISSUE THREAD

**Issue by fjphhxx** [Loop3D/LoopStructural#161]
![捕获1](https://github.com/Loop3D/LoopStructural/assets/69345724/4f685147-d143-4a95-9c26-49c5d17b68bc)
Hi lachlangrose：
I have generated strata, but I want to generate strata up and down disks. Can you tell me how to generate strata up and down disks? Thank you!

**Comment by fjphhxx** [comment]
Hi lachlangrose：
I would like to use loop to make the result shown below. It is possible to make an upper and lower disk of the strata. 
![dd](https://github.com/Loop3D/LoopStructural/assets/69345724/826636ed-efac-4a09-9697-8bf85b0d3954)
I am using loop with stratum upper disk as strati and stratum lower disk as strati3, my interpolation points are irregular but the generated model is still square. As shown in the picture below. I would like to know how to make a stratum upper and lower disk or can you give me an example of such for my reference? Thanks.
![插值点](https://github.com/Loop3D/LoopStructural/assets/69345724/9f19f824-ad77-4ef3-91f9-e670e992e343)
![面](https://github.com/Loop3D/LoopStructural/assets/69345724/f1488efe-9426-4908-9d93-0c597c93a9b3)

**Comment by lachlangrose** [comment]
@fjphhxx I don't know what you mean by stratum upper disk and lower disk... If you are talking about orientation data then you need to measure this, or define it as input to the model.

**Comment by fjphhxx** [comment]
Sorry, maybe I didn't express myself clearly. I'm trying to make the effect shown below. This picture is the one I took from your paper. If possible, could you provide me the code and data of this example for my reference. I have some confusion in the places circled in black pen. Thanks.
![ddd](https://github.com/Loop3D/LoopStructural/assets/69345724/79374fa6-954a-4711-b504-54e485b0e953)

**Comment by lachlangrose** [comment]
That is a fault, you can add a fault to your model here are some instructions https://loop3d.org/LoopStructural/user_guide/fault_modelling.html

Due to some changes in the code that model is not currently working.
