### ISSUE TITLE
How to achieve the displacement of strata at fault zones

### ISSUE THREAD

**Issue by fjphhxx** [Loop3D/LoopStructural#165]
Hi  lachlangrose:
   I can currently generate geological strata and faults, but how can I implement the displacement of strata at fault zones? I would appreciate some guidance or an example. Thank you.
![最后](https://github.com/Loop3D/LoopStructural/assets/69345724/bc5acaf3-e49d-49d3-a6fa-8a1b4a6314b6)

**Comment by lachlangrose** [comment]
Hi @fjphhxx,

have you added a displacement magntude to the fault - this needs to be in the units of the model. If it is 0 then the fault won't have any displacement.... Also make sure that the fault kinematics are included when building the fault. What is the slip vector of the fault, if the slip vector is horizontal you won't see any displacement with the horizontal layers...

**Comment by fjphhxx** [comment]
This one is your example. At the fault, the strata are not disconnected. I'm trying to figure out how I can get the strata to disconnect and show the upper and lower disks.
Thank you.
![ex](https://github.com/Loop3D/LoopStructural/assets/69345724/7d9408d1-3913-4136-b118-990d991fcf2f)
![ex2](https://github.com/Loop3D/LoopStructural/assets/69345724/d62ae559-6f3d-4e7b-93f4-df0026cf0f07)

**Comment by lachlangrose** [comment]
The scalar field of the faulted intrusion does have a discontinuity in it, but the surface is extracted from the scalar field across the fault. LoopStructural does not include any tools for dealing with this, however you could use something like pymesh to import the triangular surfaces and then cut them by the fault.

Alternatively if you increase the resultion of the viewer, this will make the cubes smaller and the fault will become more obvious.

Below uses viewer.nelements=1e6
![image](https://github.com/Loop3D/LoopStructural/assets/7371904/0cae9800-6c7d-4472-9ff9-5c050a5059b1)
