### ISSUE TITLE
Updating Issues

### ISSUE THREAD

**Issue by fjphhxx** [Loop3D/LoopStructural#181]
hi
I see that loopstructural has been updated, I have configured the environment and the version of the loopstructural is 1.5.10, now what should I do to upgrade? Because I'm running '3c. defining the fault displacement function' with an error.
![image](https://github.com/Loop3D/LoopStructural/assets/69345724/d4d15871-1e67-4c43-b4db-658be519669a)
What should I do to solve this problem, 
thanks.

**Comment by lachlangrose** [comment]
Update loopstructural, this function was only added in the latest version.
