### ISSUE TITLE
[Question] - How to update LPF stratigraphic thicknesses?

### ISSUE THREAD

**Issue by AngRodrigues** [Loop3D/LoopStructural#207]
When creating a model from map2loop, there are thicknesses that are calculated as -1, namely the top and bottom units. 
How can we update the thicknesses in processedData created with:

```
projFile = LPF.ProjectFile(loop_project_filename)
processedData = LPFProcessor(projFile)
```
?

A direct substitution doesn't seem to work, `processedData.stratigraphic_column['sg']['Pyradie_Formation']['max'] = -np.inf`
Nor `processedData.thicknesses['Turee_Creek_Group'] = np.inf`

Is there a particular method to update the thicknesses?
Thank you!

**Comment by lachlangrose** [comment]
If you try using master it should work

**Comment by AngRodrigues** [comment]
Yep, that worked. 
Thank you!
