### ISSUE TITLE
[FEATURE] Export surfaces to obj/vtk formats

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/LoopStructural#27]
**Is your feature request related to a problem? Please describe.**
Add in method to export surfaces to common formats.
 
**Describe the solution you'd like**
Either modify the LavaVuModelViewer class to save surfaces to file, or create an export class to write model objects to file (or both)

**Comment by markjessell** [comment]
Works great, except Z is -ve, and colours per fault and formation would be even greater...

**Comment by lachlangrose** [comment]
added
