### ISSUE TITLE
Getting started in Python 3.8 environment - problems

### ISSUE THREAD

**Issue by GloriaArienti** [Loop3D/LoopStructural#55]
Successfully installed LoopStructural with 'pip install LoopStructural' in Anaconda Prompt. Then I opened the project in PyCharm with a Python 3.8 Environment but I cannot run any of the examples in the 'examples' folder, such as 'example_surfe', 'plot_2_surface_modelling'... 
Any help in running these in Python 3.8 environment would be really appreciated. Thanks!

**Comment by lachlangrose** [comment]
Hi Gloria, 

What errors are you having when you tried to run the examples? Can you import loopstructural into your python environment?

cheers
