### ISSUE TITLE
[BUG] Docker not working?

### ISSUE THREAD

**Issue by bistek** [Loop3D/LoopStructural#56]
Hello, I tried to run LoopStructural with Docker, following your instructions, but I cannot have it working.

I am running Docker on Windows 10 64bit, but this should not matter (I guess).

I pull the image with `docker pull lachlangrose/loopstructural` and it seems OK in Docker Desktop:

![image](https://user-images.githubusercontent.com/12087912/110676871-c39f9f00-81d4-11eb-9e40-9aa8359de835.png)

Then I start the container with `docker run -it -p 8888:8888 lachlangrose/loopstructural` and I get:

```
[I 18:14:31.073 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 18:14:31.413 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:14:31.441 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 18:14:31.980 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 18:14:31.980 NotebookApp] Jupyter Notebook 6.1.1 is running at:
[I 18:14:31.981 NotebookApp] http://1d6ee7319fc7:8888/
[I 18:14:31.981 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

...so I copy the link `http://1d6ee7319fc7:8888/` and paste it into Firefox, but I get this error:

![image](https://user-images.githubusercontent.com/12087912/110677262-4163aa80-81d5-11eb-9986-97d1fb49f7fa.png)

I also tried starting the image from Docker Desktop, and apparently it runs, but with no browser output:

![image](https://user-images.githubusercontent.com/12087912/110677447-78d25700-81d5-11eb-877a-f410a4172a7b.png)

Do you have any suggestion?

Thanks very much!

**Comment by lachlangrose** [comment]
Hi Andrea,

The URL you are trying to access on the docker container is the local address for the docker image, this is port forwarded to the host port 8888 (the command -p 8888:8888 maps 8888 on the container to 8888 on the host), so you should be able to access it by going to localhost:8888. I'll have to add a message to the docker container that prints this out on start up to make it easier!

You would be better using the loop3d/loopstructural docker image as this is more up to date. I have also created another image that includes map2loop, surfe, loopstructural and the ensemble generator which is on loop3d/loop. You can start them in the same way that you have. 

Good luck!

**Comment by bistek** [comment]
Hello and thanks, now it works. My fault (stupid joke for a geologist)!

There are no example notebooks. Do you suggest to use the code in the examples folder on GIT?

And... suppose I like to clone the repo and run it directly. What are the requirements? I have seen that you have a **conda** directory suggesting that it can be installed that way?

Thanks!!

**Comment by lachlangrose** [comment]
Hi,

With the docker container you can map a folder on your own computer to the docker container. see [setting up docker](https://loop3d.github.io/LoopStructural/installation.html#docker), you can then download in the folder some [example notebooks from the documentation ](https://loop3d.github.io/LoopStructural/auto_examples/index.html). I will make a new repository for the examples to make this easy to do.

Cheers
