### ISSUE TITLE
Visualization of geological model object with pyvista[Question]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#69]
Hi,

Is it possible to visualize the geological model object in loopstructural3D with another visualization library e.g pyvista. Any help would be greatly appreciated,
thanks,

cheers,

**Comment by markjessell** [comment]
Hi. LoopStructural can save out surfaces in both vtk and obj formats, both of which I believe pyvista can load and display.

Cheers
Mark

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E ***@***.***

________________________________
From: mustaeenqazi ***@***.***>
Sent: Tuesday, June 22, 2021 7:59:32 PM
To: Loop3D/LoopStructural ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Loop3D/LoopStructural] Visualization of geological model object with pyvista[Question] (#69)


Hi,

Is it possible to visualize the geological model object in loopstructural3D with another visualization library e.g pyvista. Any help would be greatly appreciated,
thanks,

cheers,

**Comment by mustaeenqazi** [comment]
Thank you very much.

Cheers,
Mustaeen Qazi

**Comment by lachlangrose** [comment]
Just a comment on that, currently to save the vtk surfaces you need to use the LavaVuViewer. It is something I will work on to change.

**Comment by markjessell** [comment]
Good point. You can see how to save out both file formats in the LoopStructural section of this notebook:

https://github.com/Loop3D/map2loop2-notebooks/blob/master/Example%202%20-%20Draw%20Your%20Own%20Area.ipynb

cheers

Mark

**Comment by mustaeenqazi** [comment]
Thanks for your help with this issue. :)
Cheers,
Mustaeen
