### ISSUE TITLE
LoopStructural.modelling.core.geological_model ~ WARNING    ~ No data for Darling, skipping[BUG]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#74]
Hi,
I get the warning "No data for Darling(name of the formation) when i run:
![data_example](https://user-images.githubusercontent.com/66418760/131667436-6c30df2f-816b-42fa-89a8-f7e6aefa4e09.JPG)
![formation](https://user-images.githubusercontent.com/66418760/131667438-8f2bb088-0349-4bff-8736-6d7d8ada36aa.JPG)

model.create_and_add_foliation("Darling",
                                           interpolatortype="PLI", 
                                           nelements=1e4, 
                                           buffer=0.3,
                                           solver='pyamg',
                                           damp=True
                                          )

Darling is the formation for which i have the dip and azimuth.

The data i have is attached as a screenshot with this report.

LoopStructural/modelling/core/geological_model.py line 605 to 609 it gives the reason for warning,

# add data
        series_data = self.data[self.data['feature_name'] == series_surface_data]
        if series_data.shape[0] == 0:
            logger.warning("No data for %s, skipping" % series_surface_data)
            return

 which seems not the case with my data.

**Comment by mustaeenqazi** [comment]
Thank you very much, Yes i figured this and changed the name of the column to "feature_name". This error is gone, but there is another error, while running the same code, somehow the interpolator is getting a "None_type object and cannot set the property name". The error message and the code which generates the error are attached hereby in this comment. Please have a look
![
![data_2](https://user-images.githubusercontent.com/66418760/131920973-783874d4-8bad-4558-8fd0-fb873d31d246.JPG)





![attribute_error](https://user-images.githubusercontent.com/66418760/131921672-abdbca46-f1f9-4597-af62-1694e730f923.JPG)
![code_with_attribute error](https://user-images.githubusercontent.com/66418760/131921708-888203fa-d8b0-4aa1-a965-0bd125af04f8.JPG)

**Comment by lachlangrose** [comment]
Hi, 

The error "Cannot create interpolator: number of steps is too small" suggests that you need to increase the resolution of the model. LoopStructural uses cubic elements for interpolation so the x,y,z dimensions of the elements are equal. This means for areas with a large map extent and a thin model if a small number of elements are used the number of steps in z is automatically calculated to be too small. If you try increasing nelements this error should go away. Maybe nelements=5e4.

Good luck

**Comment by mustaeenqazi** [comment]
thank you very much for input, the bug for which I raised the issue originally, is solved so i will close the Issue, and describe the new bug in detail in next issue.
