### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_property_name'[BUG]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#75]
Hi, 
I am running the code to create the model and I keep getting the Attribute error "NoneType' object has no attribute 'set_property_name".
Although every thing else works, the problem comes from the file geological_feature_builder.py line 39.         self._interpolator.set_property_name(self._name). 
I dont understand why the interpolator needs to set the property name, it could be any property, secondly this function is being applied to "self.name" which also causes confusion as to what name, the property name or the name of formation?.

An important consideration, i don't have the column for "vals" in my data, I tried to add this column with some arbitrary values just to see if the error goes away, but the error stays.

**Minimal working example**
The minimal code required to reproduce the bug:

vals = [0,100,250,330,600]

strat_column = {'Permian':{}}
for i in range(len(vals)-1):
    strat_column['Permian']['unit_{}'.format(i)] = {'min':vals[i],'max':vals[i+1],'id':i}  
    
model.set_stratigraphic_column(strat_column)

formation = model.create_and_add_foliation("Permian",
                                           interpolatortype="FDI", # try changing this to 'PLI'
                                           nelements=5e4, # try changing between 1e3 and 5e4
                                           buffer=0.3,
                                           solver='pyamg',
                                           damp=True
                                          )

**Expected behavior**
Computation of the desired geological model.

**Screenshots**

![attribute_error](https://user-images.githubusercontent.com/66418760/132097838-bf4b9f6c-c4d1-41ab-8ac1-6fe78aa51686.JPG)

**Comment by lachlangrose** [comment]
Most of the time the interpolator does not need to have a property name but if you want to interpolate two properties on the same support it is used to differentiate the results. I will remove this in the future as it is not used in LoopStructural anymore but it is not the cause of the bug you are having.

Without seeing your data or the whole code used to create the model I can't really help. The interpolator is not being created, but I don't know why. Are you seeing a warning "Interpolator not created"?

**Comment by lachlangrose** [comment]
Can you include the model definition please. I need to see the min/max for
the model.

**Comment by mustaeenqazi** [comment]
Hi,

Thanks for your input on this bug, and helping to understand. The bug is solved by adding the line: "model.set_model_data(data)" , before using the line: "model.create_and_add_foliation()". I dont understand why i need to use this because the data is already set, but it somehow makes the code work.

Cheers,

**Comment by lachlangrose** [comment]
You have created a dataframe for the data but LoopStructural uses an object-oriented program design meaning that the data needs to be an attribute of the model. This process makes a copy of the dataframe so the original data are not modified, transforms the data so that the origin of the model is [0,0,0] and converts strike and dip to normal vectors.

**Comment by mustaeenqazi** [comment]
Okay i understand it now. Thank you for your input!!

Cheers,
Mustaeen
