### ISSUE TITLE
Runtime error when using RBF(surfe) as interpolator type[BUG]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#78]
I am using the 'RBF' interpolator called 'surfe' to creater foliations, the model is created but when i use the Lavavuviewr to plot the iso-surfaces by using :

viewer.add_isosurface(formation_Coomallo, slices=[0,-60,-250,-330],
                     paint_with=formation_Coomallo)
                      
                      

i get the following error:

![runtime_error1](https://user-images.githubusercontent.com/66418760/132993445-32451c6b-ad41-481c-afbc-b814307fb36d.JPG)

![runtime_error2](https://user-images.githubusercontent.com/66418760/132993452-2429b63b-531b-4db1-946a-5e6bed9b2c59.JPG)

![runtime_error3](https://user-images.githubusercontent.com/66418760/132993464-5bc15df7-296b-48e3-97ad-90f34cccd063.JPG)

**Comment by lachlangrose** [comment]
The RuntimeError is raised by surfe due to "No interface data". 

Can you show me what data is associated with "formation_Coomallo".

**Comment by mustaeenqazi** [comment]
hi,
Yes the error message says: "No interface data". But the same data works fine in visualizing, when I am using FDI and PLI as interpolators. I dont understand why does the Lavavu viewer, needs the interpolator and the interface data? As i have already created the model and just want to view it. For example i have already created the foliation as following image, and it works fine without any error:
![creating_foliation](https://user-images.githubusercontent.com/66418760/133046902-615d185f-6fdb-49c8-b548-0caf4afacf46.JPG)


after this i want to visualize the created foliation using:

![add_iso_surface](https://user-images.githubusercontent.com/66418760/133047996-a93f242c-09ce-4c69-9923-b9695d7037f2.JPG)


The data is attached in the following image. The same problem happens if i use the formation_permian, so i attach the data for permian:
![data](https://user-images.githubusercontent.com/66418760/133046564-386e4973-5095-41c0-8312-b57cfc065a0c.JPG)

**Comment by mustaeenqazi** [comment]
Hi,
by looking at the data again, i guess i figured the problem, unfortunately i was just using the code to adjust the data and didnt look at the data itself. i think some points are converted to exponential values e.g. 3.894E+11, these are interface points but because the extent of the model i.e. array bb = np.array([[337000,6640000,-18000],  
[400000,6710000,1000]]) , has lower values so the model doesnt use these exponential values.
 I will convert these exponential values to the normal XYZ values and check if the error persists.

**Comment by lachlangrose** [comment]
Ok that might be the issue.

The reason the error is occuring is the model is only calculated when model.update() is called. If you try and visualise or evaluate the interpolant value when its not up to date it will call this.

**Comment by mustaeenqazi** [comment]
the error still persists after the correction in the data.
i dont understand why i need to update although i didnt add any extra surfaces after i created the foliations. i directly visualiozed them after creating foliations.
From your comment i understand that i need to call the function model.update() before visualizing the model ? Is that Right?

**Comment by lachlangrose** [comment]
You don't need to call model.update(), it is called automatically if it hasn't been called. The interpolation is not done until model.update() is run and if you add surfaces to the model it gets called then. If you call it beforehand it will just shift where you see that error. 

Looking at surfe (not my code) I saw the error you are getting is coming from not having any interface data. Do you only have data constraining the gradient/norm of the scalar field? or do you have data points for the value of the field. 

The other interpolators will work with fewer constraints, but the results may not be reliable.

**Comment by mustaeenqazi** [comment]
Hi, 
thank you very much for your input. So after reading your comment i got an insight, as the available data for the model doesn't have any data for the value of the field/ formation, and the RBF functions need this data to interpolate unlike the other two interpolators. I added a column of value data to the original data and gave each formation a number, e.g i have 5 formations so i gave each one a number from 1 to 5. The RBF function works now. Although the results are abit unrealistic, I am trying to figure out other problems.

**Comment by lachlangrose** [comment]
Hi,

When using surfe there are two different ways that the interpolator can consider the problem. 1) Is the implicit function representing the distance from a reference horizon, in this case the values you uses should be the expected thickness of the units. 2) each value represents points which have the same value of the implicit function (this is the same as used in geomodeller and gempy). This approach requires you to have gradient normal constraints in between the interfaces.

To use method 1), use the default the kwarg method='single_surface', to use 2) use method='Laujaunie'

What you have describes would work well with the laujaunie method, but be aware you rely a lot on the gradient norm constraints and not so much on the other observations. If you can estimate the thickness of the layers the value can be the cummulative thickness from the base layer. 

Hopefully this helps.

**Comment by mustaeenqazi** [comment]
Thank you very much, for your input.  So i can calculate the cummulative thickness of each formation starting from bottom most formation, and use it as "val"/ value constraints. And use the Laujaunie method with it?
