### ISSUE TITLE
AttributeError: 'SurfeRBFInterpolator' object has no attribute 'copy'[BUG]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#79]
Hi,
I am trying to create Faults using the RBF (surfe) interpolator. And i get the attribute error as mentioned in the heading. The error doesnot arise when i create a foliation instead of fault.

Here is the code that produces the error:

![code_to_generate_fault_surfe_attribute_error](https://user-images.githubusercontent.com/66418760/133776087-ae235eaf-3fc3-44a5-96ed-ada77854b7c3.JPG)

Expected behavior_

add a fault surface to the model

**Screenshots**
![attribute_error_creating_fault_with_surfe](https://user-images.githubusercontent.com/66418760/133776210-d3d95a4a-74c3-4408-afdd-df5c3f4afcd3.JPG)

![attribute_error_creating_fault_with_surfe2](https://user-images.githubusercontent.com/66418760/133776220-78060845-7afd-4c19-8927-96c6d5222f3d.JPG)

Additionally!! The fault is created and added to the model when i Use PLI as the interpolator, but i cannot visualize it somehow. i guess that can be another bug/error.

**Comment by lachlangrose** [comment]
It is currently not possible to use surfe to build a fault frame so unfortunately, you can't interpolate faults using surfe. I will add in an error for catching this and it is on my list of jobs to implement faults using surfe but not a priority. 

I can't help with the other error without having some more information, how did you try and add the fault to the model?

**Comment by mustaeenqazi** [comment]
Thank you very much. Would be great if we can add faults with surfe, sometime later hopefully. 

I added the fault using the code:

model.create_and_add_fault() and interpolator type as PLI. 

The generated warning says: "cannot isosurface fault at isovalue..."

 So i changed the iso values for faults to '0' and now i can visualize the faults. I will create another error report on this issue, as there are also some other surfaces which cannot be visualized. But for now it is enough to visualize a few.
